#!/usr/bin/env python3
"""
Train LightGBM ETA model.

Usage:
  python train_eta.py

Input:
  synthetic_routes_df.csv (generated by generate_synthetic_data.py)

Output:
  eta_model.txt (LightGBM model — text format, loadable by sidecar)

Requires:
  pip install lightgbm pandas scikit-learn

Note:
  Phase 4 MVP uses synthetic training data.
  In Phase 5+, replace synthetic_routes_df.csv with Google Maps Directions API data.
"""

import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Feature order MUST match:
# - generate_synthetic_data.py
# - Node.js eta_model.js extractEtaFeatures()
# - Python sidecar.py /predict endpoint
FEATURES = [
    'distance_km',
    'turn_count',
    'hour_of_day',
    'day_of_week',
    'hazard_count',
    'avg_speed_limit'
]
TARGET = 'eta_minutes'


def main():
    # Load synthetic training data
    print('Loading synthetic training data...')
    df = pd.read_csv('synthetic_routes_df.csv')
    print(f'  Loaded {len(df)} samples')

    X = df[FEATURES]
    y = df[TARGET]

    # Train/test split (80/20, deterministic)
    print('Splitting data...')
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    print(f'  Train: {len(X_train)} samples')
    print(f'  Test: {len(X_test)} samples')

    # Train LightGBM
    print('Training LightGBM model...')
    model = lgb.LGBMRegressor(
        n_estimators=100,
        learning_rate=0.1,
        num_leaves=31,
        verbose=-1,
        random_state=42,
    )
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse ** 0.5
    mae = mean_absolute_error(y_test, y_pred)

    print(f'Model evaluation:')
    print(f'  RMSE: {rmse:.2f} minutes')
    print(f'  MAE:  {mae:.2f} minutes')

    # Save model (LightGBM text format)
    print('Saving model...')
    model.booster_.save_model('eta_model.txt')
    print(f'  ✓ Saved: eta_model.txt')
    print()
    print('✓ Training complete. Model ready for sidecar.')


if __name__ == '__main__':
    main()
